[package]
name = "keyboard-controller"
version = "0.1.0"
authors = ["Edouard Menayde <scrunshes@gmail.com>"]

[dependencies]
dbus = "0.5.2"
time = "0.1"
json = "*"
log = "*"
env_logger = "*"
gdk-pixbuf = "0.1.3"

[dependencies.gtk]
version = "0.1.3"
features = ["v3_20"]